// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.Achievements.AchievementPost", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostId"));

                    b.Property<string>("AttachmentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("attachment_filename");

                    b.Property<string>("AttachmentPublicId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attachment_public_id");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attachment_url");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit")
                        .HasColumnName("is_system_generated");

                    b.Property<int>("PostType")
                        .HasColumnType("int")
                        .HasColumnName("post_type");

                    b.Property<string>("SystemKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("system_key");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("post_visibility");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("achievement_posts");
                });

            modelBuilder.Entity("backend.Entities.Achievements.CommentLike", b =>
                {
                    b.Property<long>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_like_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LikeId"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_comment_id");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("liked_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("LikeId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("comment_likes");
                });

            modelBuilder.Entity("backend.Entities.Achievements.PostComment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentId"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_author_id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_parent_comment_id");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_post_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("post_comments");
                });

            modelBuilder.Entity("backend.Entities.Achievements.PostLike", b =>
                {
                    b.Property<long>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_like_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LikeId"));

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("liked_at");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_post_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("LikeId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("post_likes");
                });

            modelBuilder.Entity("backend.Entities.Achievements.RemovedContent", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_author_id");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_content_id");

                    b.Property<int>("ContentType")
                        .HasColumnType("int")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DeletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_deleted_by");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.HasKey("LogId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeletedBy");

                    b.ToTable("removed_contents");
                });

            modelBuilder.Entity("backend.Entities.Common.EmailLog", b =>
                {
                    b.Property<long>("EmailLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_email_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmailLogId"));

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_type");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_job_id");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("recipient_email");

                    b.Property<long?>("ReferralId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_referral_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.HasKey("EmailLogId");

                    b.ToTable("email_logs");
                });

            modelBuilder.Entity("backend.Entities.Common.GlobalConfig", b =>
                {
                    b.Property<long>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigId"));

                    b.Property<string>("ConfigField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("config_field");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("config_value");

                    b.Property<string>("RelatedTable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("related_table");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigField")
                        .IsUnique();

                    b.ToTable("global_config");
                });

            modelBuilder.Entity("backend.Entities.Common.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("backend.Entities.Common.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("backend.Entities.Common.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_joining");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_manager_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profile_photo_url");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hash_refresh_token");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Entities.Common.UserRefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_refresh_tokens");
                });

            modelBuilder.Entity("backend.Entities.Games.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_game_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("game_name");

                    b.Property<int>("MaxPlayersPerSlot")
                        .HasColumnType("int")
                        .HasColumnName("max_players_per_slot");

                    b.Property<TimeSpan>("OperatingHoursEnd")
                        .HasColumnType("time")
                        .HasColumnName("operating_hours_end");

                    b.Property<TimeSpan>("OperatingHoursStart")
                        .HasColumnType("time")
                        .HasColumnName("operating_hours_start");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("slot_duration_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("GameId");

                    b.HasIndex("GameName")
                        .IsUnique();

                    b.ToTable("games");
                });

            modelBuilder.Entity("backend.Entities.Games.GameBooking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("booking_date");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_created_by");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_game_id");

                    b.Property<TimeSpan>("SlotEndTime")
                        .HasColumnType("time")
                        .HasColumnName("slot_end_time");

                    b.Property<long>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_slot_id");

                    b.Property<TimeSpan>("SlotStartTime")
                        .HasColumnType("time")
                        .HasColumnName("slot_start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("BookingId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GameId");

                    b.HasIndex("SlotId");

                    b.ToTable("game_bookings");
                });

            modelBuilder.Entity("backend.Entities.Games.GameBookingParticipant", b =>
                {
                    b.Property<long>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_participant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParticipantId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_booking_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("ParticipantId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("game_booking_participants");
                });

            modelBuilder.Entity("backend.Entities.Games.GameHistory", b =>
                {
                    b.Property<long>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_stat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatId"));

                    b.Property<DateTime>("CycleEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("cycle_end_date");

                    b.Property<DateTime>("CycleStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("cycle_start_date");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_game_id");

                    b.Property<DateTime?>("LastPlayedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_played_date");

                    b.Property<int>("SlotsPlayed")
                        .HasColumnType("int")
                        .HasColumnName("slots_played");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("StatId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId", "CycleStartDate", "CycleEndDate")
                        .IsUnique();

                    b.ToTable("game_history");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlot", b =>
                {
                    b.Property<long>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_slot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SlotId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_game_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("SlotId");

                    b.HasIndex("GameId");

                    b.ToTable("game_slots");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlotRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_requested_by");

                    b.Property<long>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("SlotId");

                    b.ToTable("game_slot_requests");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlotRequestParticipant", b =>
                {
                    b.Property<long>("RequestParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_request_participant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestParticipantId"));

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_request_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("RequestParticipantId");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("game_slot_request_participants");
                });

            modelBuilder.Entity("backend.Entities.Games.UserGameInterest", b =>
                {
                    b.Property<long>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_interest_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InterestId"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_game_id");

                    b.Property<bool>("IsInterested")
                        .HasColumnType("bit")
                        .HasColumnName("is_interested");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("registered_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_user_id");

                    b.HasKey("InterestId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("user_game_interests");
                });

            modelBuilder.Entity("backend.Entities.Referrals.JobOpening", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_job_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobId"));

                    b.Property<string>("CvReviewerEmails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cv_reviewer_emails");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("ExperienceRequired")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("experience_required");

                    b.Property<string>("HrOwnerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hr_owner_email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("JobDescriptionPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("job_description_path");

                    b.Property<string>("JobSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_summary");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_title");

                    b.Property<int>("JobType")
                        .HasColumnType("int")
                        .HasColumnName("job_type");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("posted_at");

                    b.Property<long?>("PostedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_posted_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId");

                    b.HasIndex("PostedBy");

                    b.ToTable("job_openings");
                });

            modelBuilder.Entity("backend.Entities.Referrals.JobShare", b =>
                {
                    b.Property<long>("ShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_share_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShareId"));

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_job_id");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("recipient_email");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("shared_at");

                    b.Property<long>("SharedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_shared_by");

                    b.HasKey("ShareId");

                    b.HasIndex("JobId");

                    b.HasIndex("SharedBy");

                    b.ToTable("job_shares");
                });

            modelBuilder.Entity("backend.Entities.Referrals.Referral", b =>
                {
                    b.Property<long>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_referral_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReferralId"));

                    b.Property<string>("CvFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cv_file_path");

                    b.Property<string>("FriendEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("friend_email");

                    b.Property<string>("FriendName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("friend_name");

                    b.Property<string>("HrRecipients")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hr_recipients");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_job_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("ReferredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_referred_by");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("status_updated_at");

                    b.Property<long?>("StatusUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_status_updated_by");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("ReferralId");

                    b.HasIndex("JobId");

                    b.HasIndex("ReferredBy");

                    b.HasIndex("StatusUpdatedBy");

                    b.ToTable("referrals");
                });

            modelBuilder.Entity("backend.Entities.Referrals.ReferralStatusLog", b =>
                {
                    b.Property<long>("ReferralStatusLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_referral_status_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReferralStatusLogId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<long?>("ChangedById")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_changed_by");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int")
                        .HasColumnName("old_status");

                    b.Property<string>("RecipientsSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recipients_snapshot");

                    b.Property<long>("ReferralId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_referral_id");

                    b.HasKey("ReferralStatusLogId");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ReferralId");

                    b.ToTable("referral_status_logs");
                });

            modelBuilder.Entity("backend.Entities.Travels.Expense", b =>
                {
                    b.Property<long>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_expense_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_employee_id");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expense_date");

                    b.Property<string>("HrRemarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hr_remarks");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<long>("TravelId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_travel_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TravelId");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("backend.Entities.Travels.ExpenseCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("MaxAmountPerDay")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("max_amount_per_day");

                    b.HasKey("CategoryId");

                    b.ToTable("expense_categories");
                });

            modelBuilder.Entity("backend.Entities.Travels.ExpenseProof", b =>
                {
                    b.Property<long>("ProofId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_proof_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProofId"));

                    b.Property<long>("ExpenseId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_expense_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("ProofId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("expense_proofs");
                });

            modelBuilder.Entity("backend.Entities.Travels.Travel", b =>
                {
                    b.Property<long>("TravelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_travel_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TravelId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_created_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("destination");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("TravelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("travel_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TravelId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("travels");
                });

            modelBuilder.Entity("backend.Entities.Travels.TravelAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_employee_id");

                    b.Property<long>("TravelId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_travel_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TravelId");

                    b.ToTable("travel_assignments");
                });

            modelBuilder.Entity("backend.Entities.Travels.TravelDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_document_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("document_type");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_employee_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_type");

                    b.Property<long>("TravelId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_travel_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_uploaded_by");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TravelId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("travel_documents");
                });

            modelBuilder.Entity("backend.Entities.Achievements.AchievementPost", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("backend.Entities.Achievements.CommentLike", b =>
                {
                    b.HasOne("backend.Entities.Achievements.PostComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Achievements.PostComment", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Entities.Achievements.PostComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backend.Entities.Achievements.AchievementPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("backend.Entities.Achievements.PostLike", b =>
                {
                    b.HasOne("backend.Entities.Achievements.AchievementPost", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Achievements.RemovedContent", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "OriginalAuthor")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Moderator");

                    b.Navigation("OriginalAuthor");
                });

            modelBuilder.Entity("backend.Entities.Common.Notification", b =>
                {
                    b.HasOne("backend.Entities.Common.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Entities.Common.User", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.Common.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Entities.Common.UserRefreshToken", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Games.GameBooking", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Games.Game", "Game")
                        .WithMany("Bookings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Games.GameSlot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Game");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("backend.Entities.Games.GameBookingParticipant", b =>
                {
                    b.HasOne("backend.Entities.Games.GameBooking", "Booking")
                        .WithMany("Participants")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Games.GameHistory", b =>
                {
                    b.HasOne("backend.Entities.Games.Game", "Game")
                        .WithMany("Histories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlot", b =>
                {
                    b.HasOne("backend.Entities.Games.Game", "Game")
                        .WithMany("Slots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlotRequest", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Games.GameSlot", "Slot")
                        .WithMany("Requests")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlotRequestParticipant", b =>
                {
                    b.HasOne("backend.Entities.Games.GameSlotRequest", "Request")
                        .WithMany("Participants")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Games.UserGameInterest", b =>
                {
                    b.HasOne("backend.Entities.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Referrals.JobOpening", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Poster")
                        .WithMany()
                        .HasForeignKey("PostedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("backend.Entities.Referrals.JobShare", b =>
                {
                    b.HasOne("backend.Entities.Referrals.JobOpening", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "Sharer")
                        .WithMany()
                        .HasForeignKey("SharedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Sharer");
                });

            modelBuilder.Entity("backend.Entities.Referrals.Referral", b =>
                {
                    b.HasOne("backend.Entities.Referrals.JobOpening", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "StatusUpdater")
                        .WithMany()
                        .HasForeignKey("StatusUpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Job");

                    b.Navigation("Referrer");

                    b.Navigation("StatusUpdater");
                });

            modelBuilder.Entity("backend.Entities.Referrals.ReferralStatusLog", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.Referrals.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("backend.Entities.Travels.Expense", b =>
                {
                    b.HasOne("backend.Entities.Travels.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "Reviewer")
                        .WithMany("ExpensesReviewed")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.Travels.Travel", "Travel")
                        .WithMany("Expenses")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");

                    b.Navigation("Reviewer");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("backend.Entities.Travels.ExpenseProof", b =>
                {
                    b.HasOne("backend.Entities.Travels.Expense", "Expense")
                        .WithMany("ProofDocuments")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("backend.Entities.Travels.Travel", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Creator")
                        .WithMany("TravelsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("backend.Entities.Travels.TravelAssignment", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Employee")
                        .WithMany("TravelAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Travels.Travel", "Travel")
                        .WithMany("Assignments")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("backend.Entities.Travels.TravelDocument", b =>
                {
                    b.HasOne("backend.Entities.Common.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.Travels.Travel", "Travel")
                        .WithMany("Documents")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Common.User", "Uploader")
                        .WithMany("TravelDocumentsUploaded")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Travel");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("backend.Entities.Achievements.AchievementPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("backend.Entities.Achievements.PostComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("backend.Entities.Common.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Entities.Common.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("ExpensesReviewed");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TravelAssignments");

                    b.Navigation("TravelDocumentsUploaded");

                    b.Navigation("TravelsCreated");
                });

            modelBuilder.Entity("backend.Entities.Games.Game", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Histories");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("backend.Entities.Games.GameBooking", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("backend.Entities.Games.GameSlotRequest", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("backend.Entities.Travels.Expense", b =>
                {
                    b.Navigation("ProofDocuments");
                });

            modelBuilder.Entity("backend.Entities.Travels.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("backend.Entities.Travels.Travel", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Documents");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
